import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ReduxProvider } from "../../Providers/ReduxProvider ";
import HeroNav from "@/components/HeroNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased dark:bg-slate-800 ">
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-[90%] mx-auto min-h-screen relative overflow-hidden">
              <nav>
                <Navbar />
              </nav>
              <section><HeroNav /></section>
              <main>{children}</main>
            </div>
            <footer className="bg-gray-800">
              <Footer />
            </footer>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
